import { getStore } from "@netlify/blobs";

type InventoryItem = {
  id: string; name: string; emoji: string; category: string; quantity: number; unit: string;
  minQuantity: number; estimatedExpiresAt: number | null; condition: string; confidence: number;
  source: string; updatedAt: number; status: "active" | "consumed" | "discarded";
};
type ShoppingItem = { id: string; name: string; amount: number; unit: string; reason: string; checked: boolean; autoGenerated: boolean; createdAt: number };
type State = {
  inventory: InventoryItem[];
  shopping: ShoppingItem[];
  stats: { totalSaved: number; itemsRescued: number; mealsCooked: number };
  feedback: Array<{ id: string; kind: string; content: string; contact: string | null; createdAt: number }>;
  scans: number[];
};
type AuthUser = { id: string; username: string; usernameKey: string; salt: string; passwordHash: string; createdAt: number };
type Session = { userId: string; expiresAt: number };

const MODEL = process.env.VISION_MODEL || "deepseek-v4-flash-vision-exp";
const BASE_URL = (process.env.VISION_API_BASE_URL || "https://api.deepseek.com").replace(/\/$/, "");
const DAY = 86_400_000;
const systemPrompt = `你是“懒人餐 Agent”的视觉食材分析器。只识别图片里确实可见、可食用的食材，保守估计数量；观察萎蔫、变色、碰伤、霉斑、包装鼓包等可见状态，但不得声称仅凭照片能判断食品安全。estimated_days 是冷藏条件下建议再次检查或优先吃掉的天数。推荐 3 道中国年轻人在出租屋能完成的简单菜，优先消耗状态较差和已开封食材，默认有油盐、生抽和水；按用户饮食目标调整一人份用量、烹饪方式和蛋白质优先级，不得编造图片里没有的主食材。为每道菜给出一人份 calories、protein、oilGrams，以及 nutrition 食材克数清单；nutrition 只列实际下锅的主要食材，不列油盐、水和调味品，grams 是可食部分的合理估算并须与步骤和目标份量一致。客户端会优先用食材克数和营养数据重新计算；所有数值只作日常参考，不作为医疗或精确营养建议。只返回 JSON：{"summary":"短句","items":[{"name":"番茄","amount":"2 个","freshness":"尽快吃|还新鲜|耐放","emoji":"🍅","category":"蔬菜|水果|蛋白质|冷藏|主食|其他","condition":"可见状态短句","confidence":0.0,"estimated_days":2}],"recipes":[{"name":"菜名","subtitle":"一句话","time":12,"difficulty":"很简单","uses":["食材"],"missing":["缺少食材"],"saved":28,"calories":520,"protein":25,"nutrition":[{"name":"熟米饭","grams":200},{"name":"鸡蛋","grams":100},{"name":"番茄","grams":150}],"oilGrams":8,"goalNote":"为什么适合当前目标","steps":["步骤1","步骤2","步骤3"],"color":"tomato|mint|lemon","emoji":"🍅"}],"safety_note":"视觉只能辅助判断；异味、发黏、霉变或包装异常时不要食用。"}`;

function cookieValue(req: Request, name: string) {
  for (const part of (req.headers.get("cookie") || "").split(";")) {
    const [key, ...value] = part.trim().split("=");
    if (key === name) return decodeURIComponent(value.join("="));
  }
  return null;
}

function toHex(value: ArrayBuffer | Uint8Array) {
  const bytes = value instanceof Uint8Array ? value : new Uint8Array(value);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

function randomToken() {
  return Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("base64url");
}

async function sha256(value: string) {
  return toHex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)));
}

async function passwordHash(password: string, salt: string) {
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]);
  return toHex(await crypto.subtle.deriveBits({ name: "PBKDF2", hash: "SHA-256", salt: new TextEncoder().encode(salt), iterations: 160_000 }, key, 256));
}

function sameHash(left: string, right: string) {
  if (left.length !== right.length) return false;
  let different = 0;
  for (let index = 0; index < left.length; index += 1) different |= left.charCodeAt(index) ^ right.charCodeAt(index);
  return different === 0;
}

function usernameKey(value: string) {
  return value.normalize("NFKC").trim().toLocaleLowerCase("zh-CN");
}

const authStore = () => getStore("lazy-meal-auth");

async function owner(req: Request) {
  const token = cookieValue(req, "lm_session");
  if (!token) return null;
  const sessionKey = `session-${await sha256(token)}`;
  const session = await authStore().get(sessionKey, { type: "json" }) as Session | null;
  if (!session || session.expiresAt <= Date.now()) {
    if (session) await authStore().delete(sessionKey);
    return null;
  }
  const user = await authStore().get(`user-${session.userId}`, { type: "json" }) as AuthUser | null;
  return user ? { id: user.id, username: user.username } : null;
}

async function newSession(userId: string) {
  const token = randomToken();
  await authStore().setJSON(`session-${await sha256(token)}`, { userId, expiresAt: Date.now() + 30 * DAY });
  return `lm_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`;
}

function json(data: unknown, status = 200, cookie: string | null = null) {
  const headers = new Headers({ "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });
  if (cookie) headers.set("set-cookie", cookie);
  return new Response(JSON.stringify(data), { status, headers });
}

function emptyState(): State {
  return { inventory: [], shopping: [], stats: { totalSaved: 0, itemsRescued: 0, mealsCooked: 0 }, feedback: [], scans: [] };
}

async function load(id: string) {
  return (await getStore("lazy-meal-users").get(`user-${id}`, { type: "json" })) as State | null || emptyState();
}

async function save(id: string, state: State) {
  await getStore("lazy-meal-users").setJSON(`user-${id}`, state);
}

async function auth(req: Request, action: string) {
  if (action === "session" && req.method === "GET") {
    const user = await owner(req);
    return user ? json({ user }) : json({ error: "未登录" }, 401);
  }
  if (action === "logout" && req.method === "POST") {
    const token = cookieValue(req, "lm_session");
    if (token) await authStore().delete(`session-${await sha256(token)}`);
    return json({ ok: true }, 200, "lm_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0");
  }
  if ((action !== "register" && action !== "login") || req.method !== "POST") return json({ error: "接口不存在" }, 404);

  const body = await req.json();
  const username = String(body.username || "").normalize("NFKC").trim();
  const key = usernameKey(username);
  const password = String(body.password || "");
  if (!/^[\p{L}\p{N}_-]{3,24}$/u.test(username)) return json({ error: "账号需要 3–24 位中文、字母、数字、下划线或短横线" }, 400);
  if (password.length < 8 || password.length > 72) return json({ error: "密码需要 8–72 位" }, 400);

  const indexKey = `username-${await sha256(key)}`;
  const existingId = await authStore().get(indexKey, { type: "text" });
  if (action === "register") {
    if (existingId) return json({ error: "这个账号已经有人用了" }, 409);
    const user: AuthUser = { id: crypto.randomUUID(), username, usernameKey: key, salt: randomToken(), passwordHash: "", createdAt: Date.now() };
    user.passwordHash = await passwordHash(password, user.salt);
    await Promise.all([authStore().setJSON(`user-${user.id}`, user), authStore().set(indexKey, user.id)]);
    return json({ user: { id: user.id, username: user.username } }, 201, await newSession(user.id));
  }

  if (!existingId) return json({ error: "账号或密码不对" }, 401);
  const user = await authStore().get(`user-${existingId}`, { type: "json" }) as AuthUser | null;
  if (!user || !sameHash(user.passwordHash, await passwordHash(password, user.salt))) return json({ error: "账号或密码不对" }, 401);
  return json({ user: { id: user.id, username: user.username } }, 200, await newSession(user.id));
}

function categoryFor(name: string) {
  if (/蛋|肉|鸡|鱼|虾|豆腐|奶/.test(name)) return "蛋白质";
  if (/饭|面|粉|馒头|饺子|土豆/.test(name)) return "主食";
  if (/苹果|香蕉|橙|梨|葡萄/.test(name)) return "水果";
  return "蔬菜";
}

function amountParts(value: string) {
  const match = value.match(/([\d.]+)\s*(.*)/);
  return { quantity: match ? Number(match[1]) : 1, unit: match?.[2]?.trim() || "份" };
}

function expiry(item: InventoryItem) {
  if (!item.estimatedExpiresAt) return { daysLeft: null, status: "unknown", label: "日期待确认" };
  const daysLeft = Math.ceil((item.estimatedExpiresAt - Date.now()) / DAY);
  if (daysLeft < 0) return { daysLeft, status: "expired", label: "可能已过期" };
  if (daysLeft <= 2) return { daysLeft, status: "soon", label: daysLeft === 0 ? "今天优先吃" : `${daysLeft} 天内优先吃` };
  return { daysLeft, status: "fresh", label: `约 ${daysLeft} 天后检查` };
}

async function analyze(req: Request, state: State, id: string, cookie: string | null) {
  if (req.method === "GET") return json({ configured: Boolean(process.env.DEEPSEEK_API_KEY || process.env.VISION_API_KEY), provider: "DeepSeek", model: MODEL }, 200, cookie);
  const key = process.env.DEEPSEEK_API_KEY || process.env.VISION_API_KEY;
  if (!key) return json({ error: "备用站还没有配置 DeepSeek API Key。", code: "MODEL_NOT_CONFIGURED" }, 503, cookie);
  const body = await req.json();
  const goal = body.goal === "cut" || body.goal === "gain" ? body.goal : "daily";
  const goalInstruction = goal === "cut"
    ? "减脂：少油，控制精制主食份量，优先蔬菜和蛋白质，不做极端节食建议"
    : goal === "gain"
      ? "增肌：提高蛋白质和主食份量，优先训练后容易完成的一人份，不夸大效果"
      : "日常：均衡、简单并优先清理库存";
  if (typeof body.image !== "string" || !body.image.startsWith("data:image/")) return json({ error: "请上传有效图片" }, 400, cookie);
  state.scans = state.scans.filter((at) => at > Date.now() - DAY);
  if (state.scans.length >= 12) return json({ error: "今天的免费识别次数已用完，24 小时后恢复。", code: "DAILY_LIMIT" }, 429, cookie);
  const upstream = await fetch(`${BASE_URL}/chat/completions`, {
    method: "POST",
    headers: { authorization: `Bearer ${key}`, "content-type": "application/json" },
    body: JSON.stringify({ model: MODEL, temperature: 0.1, max_tokens: 3000, thinking: { type: "disabled" }, response_format: { type: "json_object" }, messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: [{ type: "text", text: `分析这张冰箱或食材照片，给出库存与今晚菜谱。当前饮食目标：${goalInstruction}。按一人份估算热量和蛋白质。` }, { type: "image_url", image_url: { url: body.image, detail: "original" } }] },
    ] }),
  });
  const payload = await upstream.json();
  if (!upstream.ok) return json({ error: payload?.error?.message || "模型暂时没有响应" }, upstream.status, cookie);
  try {
    const content = String(payload?.choices?.[0]?.message?.content || "").trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
    const parsed = JSON.parse(content);
    if (!Array.isArray(parsed.items) || !Array.isArray(parsed.recipes)) throw new Error("shape");
    state.scans.push(Date.now()); await save(id, state);
    return json({ ...parsed, goal, provider: "DeepSeek", model: MODEL }, 200, cookie);
  } catch { return json({ error: "模型结果格式不完整，请重新拍一张清晰照片" }, 502, cookie); }
}

async function inventory(req: Request, state: State, id: string, cookie: string | null) {
  if (req.method === "GET") {
    const items = state.inventory.filter((item) => item.status === "active").sort((a, b) => (a.estimatedExpiresAt || Infinity) - (b.estimatedExpiresAt || Infinity)).map((item) => ({ ...item, ...expiry(item) }));
    return json({ items, urgentCount: items.filter((item) => item.status === "soon" || item.status === "expired").length, stats: state.stats, safetyNote: "到期时间为估计；异味、发黏、霉变时请直接丢弃。" }, 200, cookie);
  }
  const body = await req.json();
  if (req.method === "POST") {
    const incoming = Array.isArray(body.items) ? body.items : [body];
    const now = Date.now();
    for (const raw of incoming.slice(0, 30)) {
      const name = String(raw.name || "").trim().slice(0, 40); if (!name) continue;
      const parsed = amountParts(String(raw.amount || "1 份"));
      const days = Math.max(0, Math.min(90, Number(raw.estimatedDays ?? raw.estimated_days ?? 4)));
      const item: InventoryItem = { id: crypto.randomUUID(), name, emoji: String(raw.emoji || "🥬"), category: String(raw.category || categoryFor(name)), quantity: Number(raw.quantity ?? parsed.quantity), unit: String(raw.unit || parsed.unit), minQuantity: Number(raw.minQuantity || 0), estimatedExpiresAt: now + days * DAY, condition: String(raw.condition || "看起来正常").slice(0, 80), confidence: Math.max(0, Math.min(1, Number(raw.confidence ?? .6))), source: String(raw.source || body.source || "manual"), updatedAt: now, status: "active" };
      const at = state.inventory.findIndex((current) => current.name === name && current.status === "active");
      if (at >= 0) state.inventory[at] = { ...item, id: state.inventory[at].id }; else state.inventory.push(item);
    }
    await save(id, state); return json({ ok: true, saved: incoming.length }, 200, cookie);
  }
  if (req.method === "PATCH") {
    const item = state.inventory.find((entry) => entry.id === String(body.id || ""));
    if (item && (body.action === "consume" || body.action === "discard")) { item.status = body.action === "consume" ? "consumed" : "discarded"; item.updatedAt = Date.now(); }
    await save(id, state); return json({ ok: true }, 200, cookie);
  }
  return json({ error: "不支持的请求" }, 405, cookie);
}

async function shopping(req: Request, state: State, id: string, cookie: string | null) {
  if (req.method === "GET") return json({ items: [...state.shopping].sort((a, b) => Number(a.checked) - Number(b.checked) || b.createdAt - a.createdAt) }, 200, cookie);
  const body = await req.json(); const now = Date.now();
  if (req.method === "POST" && body.action === "generate") {
    const active = state.inventory.filter((item) => item.status === "active" && (!item.estimatedExpiresAt || item.estimatedExpiresAt >= now));
    const names = new Set(active.map((item) => item.name));
    const suggestions: Array<{ name: string; amount: number; unit: string; reason: string }> = [];
    for (const item of active) if (item.minQuantity > 0 && item.quantity <= item.minQuantity) suggestions.push({ name: item.name, amount: Math.max(1, item.minQuantity * 2 - item.quantity), unit: item.unit, reason: "库存快见底了" });
    for (const name of (Array.isArray(body.missing) ? body.missing.map(String).slice(0, 12) : [])) if (!names.has(name)) suggestions.push({ name, amount: 1, unit: "份", reason: "想做的菜还缺它" });
    if (!active.some((item) => item.category === "蛋白质")) suggestions.push({ name: "鸡蛋", amount: 6, unit: "个", reason: "冰箱缺一份万能蛋白质" });
    if (!active.some((item) => item.category === "蔬菜")) suggestions.push({ name: "时令蔬菜", amount: 1, unit: "把", reason: "库存里没有新鲜蔬菜" });
    if (!active.some((item) => item.category === "主食")) suggestions.push({ name: "挂面", amount: 1, unit: "袋", reason: "补一个耐放的应急主食" });
    for (const suggestion of [...new Map(suggestions.map((item) => [item.name, item])).values()].slice(0, 10)) {
      const next: ShoppingItem = { id: crypto.randomUUID(), ...suggestion, checked: false, autoGenerated: true, createdAt: now };
      const at = state.shopping.findIndex((item) => item.name === suggestion.name);
      if (at >= 0) state.shopping[at] = { ...next, id: state.shopping[at].id }; else state.shopping.push(next);
    }
    await save(id, state); return json({ ok: true }, 200, cookie);
  }
  if (req.method === "POST") {
    const name = String(body.name || "").trim().slice(0, 40); if (!name) return json({ error: "要买什么？" }, 400, cookie);
    state.shopping.push({ id: crypto.randomUUID(), name, amount: Number(body.amount || 1), unit: String(body.unit || "份"), reason: "手动添加", checked: false, autoGenerated: false, createdAt: now });
    await save(id, state); return json({ ok: true }, 200, cookie);
  }
  if (req.method === "PATCH") {
    if (body.action === "clear_checked") state.shopping = state.shopping.filter((item) => !item.checked);
    else { const item = state.shopping.find((entry) => entry.id === String(body.id || "")); if (item) item.checked = Boolean(body.checked); }
    await save(id, state); return json({ ok: true }, 200, cookie);
  }
  return json({ error: "不支持的请求" }, 405, cookie);
}

export default async (req: Request) => {
  try {
    const segments = new URL(req.url).pathname.replace(/^\/api\//, "").replace(/^\/\.netlify\/functions\/api\/?/, "").split("/").filter(Boolean);
    const route = segments[0];
    if (route === "auth") return await auth(req, segments[1] || "session");
    const user = await owner(req);
    if (!user) return json({ error: "请先登录", code: "AUTH_REQUIRED" }, 401);
    const id = user.id; const cookie = null; const state = await load(id);
    if (route === "analyze") return await analyze(req, state, id, cookie);
    if (route === "inventory") return await inventory(req, state, id, cookie);
    if (route === "shopping") return await shopping(req, state, id, cookie);
    if (route === "stats" && req.method === "POST") { const body = await req.json(); state.stats.totalSaved += Math.max(0, Math.min(500, Number(body.saved || 0))); state.stats.itemsRescued += Math.max(0, Math.min(30, Number(body.rescued || 0))); state.stats.mealsCooked += 1; await save(id, state); return json({ ok: true }, 200, cookie); }
    if (route === "feedback" && req.method === "POST") { const body = await req.json(); const content = String(body.content || "").trim().slice(0, 1000); if (content.length < 5) return json({ error: "再多说一点点，至少 5 个字" }, 400, cookie); state.feedback.push({ id: crypto.randomUUID(), kind: String(body.kind || "idea"), content, contact: String(body.contact || "").trim().slice(0, 120) || null, createdAt: Date.now() }); await save(id, state); return json({ ok: true }, 200, cookie); }
    if (route === "events" && req.method === "POST") return json({ ok: true }, 200, cookie);
    return json({ error: "接口不存在" }, 404, cookie);
  } catch (error) { console.error(error); return json({ error: "备用站暂时开小差了，请稍后再试" }, 500); }
};

export const config = { path: "/api/*" };
