"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  AlertTriangle, ArrowLeft, Bell, Camera, Check, ChevronRight,
  Clock3, Refrigerator, ImagePlus, Leaf, ListPlus,
  LoaderCircle, PackageCheck, PartyPopper, Plus, RefreshCw,
  RotateCcw, ShoppingBasket, Sparkles, Trash2, Utensils,
  WandSparkles, Zap, MessageCircle, UserRound,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
import { Textarea } from "@/components/ui/textarea";
import { estimateRecipeNutrition, type NutritionIngredient } from "@/lib/nutrition";

type FoodItem = {
  name: string;
  amount: string;
  freshness: "尽快吃" | "还新鲜" | "耐放";
  emoji: string;
  category?: string;
  condition?: string;
  confidence?: number;
  estimated_days?: number;
};

type Recipe = {
  name: string; subtitle: string; time: number; difficulty: string;
  uses: string[]; missing: string[]; saved: number; steps: string[];
  color: string; emoji: string;
  calories?: number; protein?: number; goalNote?: string;
  nutrition?: NutritionIngredient[]; oilGrams?: number;
};

type MealGoal = "daily" | "cut" | "gain";

type Analysis = {
  mode?: "live" | "demo";
  provider?: string;
  model?: string;
  items: FoodItem[];
  recipes: Recipe[];
  summary: string;
  safety_note?: string;
  goal?: MealGoal;
};

type InventoryItem = {
  id: string; name: string; emoji: string; category: string;
  quantity: number; unit: string; minQuantity: number;
  estimatedExpiresAt: number | null; condition: string; confidence: number;
  source: string; updatedAt: number; daysLeft: number | null;
  status: "fresh" | "soon" | "expired" | "unknown"; label: string;
};

type ShoppingItem = {
  id: string; name: string; amount: number; unit: string; reason: string;
  checked: boolean | number; autoGenerated: boolean | number; createdAt: number;
};

type Stats = { totalSaved: number; itemsRescued: number; mealsCooked: number };
type ModelStatus = { configured: boolean; provider: string; model: string };

const demoAnalysis: Analysis = {
  mode: "demo",
  summary: "冰箱不空，今晚完全不用点外卖。先消耗番茄和剩饭最划算。",
  safety_note: "视觉只能辅助判断；异味、发黏、霉变或包装异常时不要食用。",
  items: [
    { name: "鸡蛋", amount: "2 个", freshness: "还新鲜", emoji: "🥚", category: "蛋白质", condition: "蛋壳完整", confidence: .92, estimated_days: 7 },
    { name: "番茄", amount: "1 个", freshness: "尽快吃", emoji: "🍅", category: "蔬菜", condition: "表皮略软", confidence: .87, estimated_days: 2 },
    { name: "剩米饭", amount: "1 碗", freshness: "尽快吃", emoji: "🍚", category: "主食", condition: "已冷藏，时间需确认", confidence: .74, estimated_days: 1 },
    { name: "嫩豆腐", amount: "半盒", freshness: "还新鲜", emoji: "◻️", category: "冷藏", condition: "包装已开封", confidence: .81, estimated_days: 2 },
    { name: "小葱", amount: "1 小把", freshness: "还新鲜", emoji: "🌱", category: "蔬菜", condition: "叶尖轻微萎蔫", confidence: .84, estimated_days: 3 },
    { name: "卷心菜", amount: "半颗", freshness: "耐放", emoji: "🥬", category: "蔬菜", condition: "切面正常", confidence: .89, estimated_days: 6 },
  ],
  recipes: [
    { name: "番茄鸡蛋焖饭", subtitle: "一口锅，清空昨晚的剩饭", time: 12, difficulty: "闭眼都能做", uses: ["鸡蛋", "番茄", "剩米饭", "小葱"], missing: [], saved: 28, calories: 520, protein: 22, nutrition: [{ name: "熟米饭", grams: 220 }, { name: "鸡蛋", grams: 100 }, { name: "番茄", grams: 180 }, { name: "小葱", grams: 8 }], oilGrams: 8, goalNote: "主食、蔬菜和蛋白质都有，适合均衡的一餐。", steps: ["番茄切小块，鸡蛋打散；锅里少油炒熟鸡蛋。", "倒入番茄炒出汁，加一勺生抽和两勺水。", "铺上剩饭焖 3 分钟，拌匀后撒葱花。"], color: "tomato", emoji: "🍅" },
    { name: "豆腐滑蛋汤", subtitle: "热乎、清爽，夜里吃也没负担", time: 10, difficulty: "零翻车", uses: ["鸡蛋", "嫩豆腐", "小葱"], missing: [], saved: 22, calories: 310, protein: 24, nutrition: [{ name: "嫩豆腐", grams: 220 }, { name: "鸡蛋", grams: 100 }, { name: "小葱", grams: 8 }], oilGrams: 3, goalNote: "热量更轻，豆腐和鸡蛋补足蛋白质。", steps: ["水烧开，豆腐用勺子挖成小块下锅。", "加盐和白胡椒，转小火淋入蛋液。", "关火撒葱花，喜欢的话滴两滴香油。"], color: "mint", emoji: "🥣" },
    { name: "卷心菜蛋炒饭", subtitle: "脆脆的，十分钟解决一大盘", time: 10, difficulty: "很简单", uses: ["鸡蛋", "卷心菜", "剩米饭"], missing: [], saved: 25, calories: 480, protein: 20, nutrition: [{ name: "熟米饭", grams: 220 }, { name: "鸡蛋", grams: 100 }, { name: "卷心菜", grams: 160 }], oilGrams: 10, goalNote: "碳水和蔬菜搭配，训练后也方便补充能量。", steps: ["卷心菜切丝，鸡蛋先炒散盛出。", "大火炒软菜丝，倒入米饭压散。", "鸡蛋回锅，加生抽和盐快速翻匀。"], color: "lemon", emoji: "🥬" },
  ],
};

const freshnessClass: Record<FoodItem["freshness"], string> = { "尽快吃": "urgent", "还新鲜": "fresh", "耐放": "steady" };

function blobToDataUrl(file: Blob) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

async function prepareImage(file: File) {
  if (!file.type.startsWith("image/")) throw new Error("请选择照片文件");
  if (file.size > 40 * 1024 * 1024) throw new Error("这张照片超过 40MB，换一张试试");

  const sourceUrl = URL.createObjectURL(file);
  try {
    const image = new Image();
    image.src = sourceUrl;
    await new Promise<void>((resolve, reject) => {
      image.onload = () => resolve();
      image.onerror = () => reject(new Error("这张照片暂时无法读取，请换一张或先保存为 JPG"));
    });

    const maxSide = 1536;
    const scale = Math.min(1, maxSide / Math.max(image.naturalWidth, image.naturalHeight));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(image.naturalWidth * scale));
    canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));
    const context = canvas.getContext("2d");
    if (!context) throw new Error("浏览器无法处理这张照片");
    context.drawImage(image, 0, 0, canvas.width, canvas.height);

    const toJpeg = (quality: number) => new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("照片压缩失败")), "image/jpeg", quality));
    let compressed = await toJpeg(.82);
    if (compressed.size > 2.6 * 1024 * 1024) compressed = await toJpeg(.68);
    if (compressed.size > 2.6 * 1024 * 1024) compressed = await toJpeg(.54);
    if (compressed.size > 3 * 1024 * 1024) throw new Error("照片内容太复杂，换一张稍小的试试");
    return { dataUrl: await blobToDataUrl(compressed), compressed: compressed.size < file.size, originalSize: file.size, outputSize: compressed.size };
  } finally {
    URL.revokeObjectURL(sourceUrl);
  }
}

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const cameraRef = useRef<HTMLInputElement>(null);
  const [view, setView] = useState("cook");
  const [phase, setPhase] = useState<"home" | "scanning" | "result">("home");
  const [progress, setProgress] = useState(8);
  const [preview, setPreview] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<Analysis>(demoAnalysis);
  const [notice, setNotice] = useState("");
  const [activeRecipe, setActiveRecipe] = useState(0);
  const [cooked, setCooked] = useState(false);
  const [inventory, setInventory] = useState<InventoryItem[]>([]);
  const [shopping, setShopping] = useState<ShoppingItem[]>([]);
  const [stats, setStats] = useState<Stats>({ totalSaved: 0, itemsRescued: 0, mealsCooked: 0 });
  const [safetyNote, setSafetyNote] = useState("");
  const [loadingData, setLoadingData] = useState(true);
  const [filter, setFilter] = useState<"all" | "urgent">("all");
  const [inventoryDialog, setInventoryDialog] = useState(false);
  const [shoppingDialog, setShoppingDialog] = useState(false);
  const [feedbackDialog, setFeedbackDialog] = useState(false);
  const [feedbackDraft, setFeedbackDraft] = useState({ kind: "idea", content: "", contact: "" });
  const [modelStatus, setModelStatus] = useState<ModelStatus>({ configured: false, provider: "DeepSeek", model: "deepseek-v4-flash-vision-exp" });
  const [mealGoal, setMealGoal] = useState<MealGoal>("daily");
  const [draftFood, setDraftFood] = useState({ name: "", amount: "1", unit: "份", days: "4" });
  const [draftBuy, setDraftBuy] = useState({ name: "", amount: "1", unit: "份" });

  const currentRecipe = analysis.recipes[activeRecipe] ?? demoAnalysis.recipes[0];
  const urgentItems = useMemo(() => inventory.filter((item) => item.status === "soon" || item.status === "expired"), [inventory]);
  const visibleInventory = filter === "urgent" ? urgentItems : inventory;
  const checkedShopping = shopping.filter((item) => Boolean(item.checked));

  useEffect(() => {
    const savedGoal = window.localStorage.getItem("lazy_meal_goal");
    if (savedGoal === "daily" || savedGoal === "cut" || savedGoal === "gain") setMealGoal(savedGoal);
    void refreshAll();
    void fetch("/api/analyze").then((response) => response.json()).then(setModelStatus).catch(() => undefined);
    void fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event: "app_open" }) });
  }, []);

  function chooseGoal(goal: MealGoal) {
    setMealGoal(goal);
    window.localStorage.setItem("lazy_meal_goal", goal);
  }
  useEffect(() => {
    if (phase !== "scanning") return;
    const timer = window.setInterval(() => setProgress((value) => value < 86 ? value + Math.ceil(Math.random() * 8) : value), 420);
    return () => window.clearInterval(timer);
  }, [phase]);

  async function refreshAll() {
    setLoadingData(true);
    await Promise.all([loadInventory(), loadShopping()]);
    setLoadingData(false);
  }

  async function loadInventory() {
    try {
      const response = await fetch("/api/inventory");
      if (!response.ok) return;
      const payload = await response.json();
      setInventory(payload.items || []);
      setStats(payload.stats || { totalSaved: 0, itemsRescued: 0, mealsCooked: 0 });
      setSafetyNote(payload.safetyNote || "");
    } catch { /* first load can be offline */ }
  }

  async function loadShopping() {
    try {
      const response = await fetch("/api/shopping");
      if (!response.ok) return;
      const payload = await response.json();
      setShopping(payload.items || []);
    } catch { /* first load can be offline */ }
  }

  async function analyzeImage(file: File) {
    setNotice(file.size > 2 * 1024 * 1024 ? "照片有点大，正在自动压缩…" : "正在准备照片…");
    let prepared: Awaited<ReturnType<typeof prepareImage>>;
    try { prepared = await prepareImage(file); }
    catch (error) { setNotice(error instanceof Error ? error.message : "照片处理失败，请换一张"); return; }
    const { dataUrl } = prepared;
    setPreview(dataUrl); setNotice(prepared.compressed ? "已自动压缩照片，不影响食材识别" : ""); setProgress(9); setPhase("scanning");
    try {
      const response = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image: dataUrl, goal: mealGoal }) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "识别失败");
      setAnalysis({ ...payload, mode: "live", goal: mealGoal });
    } catch (error) {
      setProgress(0);
      setPreview(null);
      setPhase("home");
      setNotice(error instanceof Error ? error.message : "真实识别失败，请重试；不会使用示例数据替代。");
      return;
    }
    setProgress(100);
    window.setTimeout(() => setPhase("result"), 450);
  }

  function runDemo() {
    void fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event: "demo_opened" }) });
    setPreview("/fridge-night.png"); setAnalysis({ ...demoAnalysis, goal: mealGoal }); setNotice("正在使用示例冰箱体验完整流程");
    setProgress(12); setPhase("scanning");
    window.setTimeout(() => setProgress(68), 500); window.setTimeout(() => setProgress(100), 1050); window.setTimeout(() => setPhase("result"), 1450);
  }

  async function saveScanToInventory() {
    const response = await fetch("/api/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: analysis.items, source: analysis.mode === "live" ? "scan" : "demo" }) });
    if (!response.ok) { toast.error("库存没存上，再试一次"); return; }
    await loadInventory();
    toast.success(`已把 ${analysis.items.length} 样食材放进库存`);
  }

  async function finishMeal() {
    if (cooked) return;
    setCooked(true);
    await fetch("/api/stats", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ saved: currentRecipe.saved, rescued: currentRecipe.uses.length }) });
    await loadInventory();
    toast.success(`今晚少点一次外卖，省下 ¥${currentRecipe.saved}`);
  }

  async function consumeItem(id: string, action: "consume" | "discard" = "consume") {
    await fetch("/api/inventory", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action }) });
    await loadInventory();
    toast.success(action === "consume" ? "好，已经从冰箱划掉了" : "已记录丢弃，下次早点提醒你");
  }

  async function addFood() {
    if (!draftFood.name.trim()) return;
    await fetch("/api/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: draftFood.name, quantity: Number(draftFood.amount), unit: draftFood.unit, estimatedDays: Number(draftFood.days), source: "manual" }) });
    setDraftFood({ name: "", amount: "1", unit: "份", days: "4" }); setInventoryDialog(false); await loadInventory(); toast.success("放进冰箱了");
  }

  async function generateShopping() {
    const missing = analysis.recipes.flatMap((recipe) => recipe.missing || []);
    await fetch("/api/shopping", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", missing }) });
    await loadShopping(); setView("shopping"); toast.success("采购单更新好了");
  }

  async function addShopping() {
    if (!draftBuy.name.trim()) return;
    await fetch("/api/shopping", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draftBuy) });
    setDraftBuy({ name: "", amount: "1", unit: "份" }); setShoppingDialog(false); await loadShopping();
  }

  async function toggleShopping(id: string, checked: boolean) {
    setShopping((items) => items.map((item) => item.id === id ? { ...item, checked } : item));
    await fetch("/api/shopping", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, checked }) });
  }

  async function finishShopping() {
    if (!checkedShopping.length) return;
    await fetch("/api/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: checkedShopping.map((item) => ({ name: item.name, quantity: item.amount, unit: item.unit, amount: `${item.amount} ${item.unit}`, estimatedDays: 5, source: "shopping" })) }) });
    await fetch("/api/shopping", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "clear_checked" }) });
    await refreshAll(); toast.success("买到的食材已经自动入库");
  }

  async function submitFeedback() {
    const response = await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(feedbackDraft) });
    const payload = await response.json();
    if (!response.ok) { toast.error(payload.error || "反馈没发出去"); return; }
    setFeedbackDraft({ kind: "idea", content: "", contact: "" }); setFeedbackDialog(false); toast.success("收到，真的有人会看这条反馈");
  }

  function reset() { setView("cook"); setPhase("home"); setPreview(null); setCooked(false); setActiveRecipe(0); setNotice(""); }

  return (
    <main className="app-shell manager-shell">
      <header className="topbar">
        <button className="brand" onClick={reset} aria-label="回到首页"><span className="brand-mark"><Utensils size={18} strokeWidth={2.8} /></span><span>懒人餐 <b>Agent</b></span></button>
        <div className="topbar-actions"><Dialog open={feedbackDialog} onOpenChange={setFeedbackDialog}><DialogTrigger asChild><button className="header-icon" aria-label="提交反馈"><MessageCircle size={17} /></button></DialogTrigger><DialogContent className="food-dialog"><DialogHeader><DialogTitle>这个冰箱管家哪里不对？</DialogTitle></DialogHeader><div className="dialog-form"><div className="feedback-kinds"><button className={feedbackDraft.kind === "bug" ? "active" : ""} onClick={() => setFeedbackDraft({ ...feedbackDraft, kind: "bug" })}>遇到问题</button><button className={feedbackDraft.kind === "idea" ? "active" : ""} onClick={() => setFeedbackDraft({ ...feedbackDraft, kind: "idea" })}>我有建议</button><button className={feedbackDraft.kind === "other" ? "active" : ""} onClick={() => setFeedbackDraft({ ...feedbackDraft, kind: "other" })}>随便说说</button></div><label>想告诉我们什么<Textarea value={feedbackDraft.content} onChange={(e) => setFeedbackDraft({ ...feedbackDraft, content: e.target.value })} placeholder="比如识别错了什么，或者你还想要什么功能…" rows={5} /></label><label>联系方式（选填）<Input value={feedbackDraft.contact} onChange={(e) => setFeedbackDraft({ ...feedbackDraft, contact: e.target.value })} placeholder="微信 / 邮箱" /></label><Button onClick={submitFeedback}>发送反馈</Button></div></DialogContent></Dialog><a className="header-icon" href="/account" aria-label="账号与同步"><UserRound size={17} /></a><button className="saved-pill alert-pill" onClick={() => setView("inventory")}><Bell size={16} /> {urgentItems.length ? <><b>{urgentItems.length}</b> 样要吃</> : <>库存安稳</>}</button></div>
      </header>

      <Tabs value={view} onValueChange={setView} className="product-tabs">
        <TabsContent value="cook" className="tab-page">
          {phase === "home" && <CookHome onDemo={runDemo} onCamera={() => cameraRef.current?.click()} onGallery={() => inputRef.current?.click()} inputRef={inputRef} cameraRef={cameraRef} onFile={analyzeImage} notice={notice} stats={stats} inventoryCount={inventory.length} modelStatus={modelStatus} mealGoal={mealGoal} onGoalChange={chooseGoal} />}
          {phase === "scanning" && <Scanning preview={preview} progress={progress} />}
          {phase === "result" && <ResultView analysis={analysis} preview={preview} notice={notice} activeRecipe={activeRecipe} setActiveRecipe={setActiveRecipe} cooked={cooked} onCook={finishMeal} onReset={reset} onSave={saveScanToInventory} onShopping={generateShopping} />}
        </TabsContent>

        <TabsContent value="inventory" className="tab-page manager-page">
          <section className="manager-heading"><div><span className="eyebrow"><Refrigerator size={14} /> 我的冰箱</span><h1>库存有数，<br /><b>别让它偷偷坏。</b></h1></div><button className="round-button" onClick={() => void loadInventory()} aria-label="刷新库存"><RefreshCw size={18} /></button></section>
          <section className="inventory-stats"><article><span>现在有</span><b>{inventory.length}</b><small>样食材</small></article><article className="warn"><span>优先吃</span><b>{urgentItems.length}</b><small>样快到期</small></article><article className="money"><span>累计省</span><b>¥{stats.totalSaved}</b><small>{stats.mealsCooked} 顿没点外卖</small></article></section>

          {urgentItems.length > 0 && <section className="reminder-card"><div className="reminder-bell"><Bell size={20} /></div><div><span>今日提醒</span><strong>{urgentItems.slice(0, 2).map((item) => item.name).join("、")}该安排上了</strong><p>先吃临期，再考虑采购。</p></div></section>}
          <section className="safety-card"><AlertTriangle size={17} /><p><b>AI 只是帮你看，不替你闻。</b>{safetyNote || "有异味、发黏、霉变或包装鼓包时，不要冒险食用。"}</p></section>

          <div className="manager-toolbar"><div className="filter-pills"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>全部 {inventory.length}</button><button className={filter === "urgent" ? "active" : ""} onClick={() => setFilter("urgent")}>快过期 {urgentItems.length}</button></div><Dialog open={inventoryDialog} onOpenChange={setInventoryDialog}><DialogTrigger asChild><Button className="small-add"><Plus size={16} /> 手动添加</Button></DialogTrigger><DialogContent className="food-dialog"><DialogHeader><DialogTitle>放进冰箱</DialogTitle></DialogHeader><div className="dialog-form"><label>食材名称<Input value={draftFood.name} onChange={(e) => setDraftFood({ ...draftFood, name: e.target.value })} placeholder="比如：牛奶" /></label><div className="form-row"><label>数量<Input type="number" min="0.1" step="0.5" value={draftFood.amount} onChange={(e) => setDraftFood({ ...draftFood, amount: e.target.value })} /></label><label>单位<Input value={draftFood.unit} onChange={(e) => setDraftFood({ ...draftFood, unit: e.target.value })} /></label></div><label>预计几天内吃掉<Input type="number" min="0" max="90" value={draftFood.days} onChange={(e) => setDraftFood({ ...draftFood, days: e.target.value })} /></label><Button onClick={addFood}>加入库存</Button></div></DialogContent></Dialog></div>

          {loadingData ? <LoadingCards /> : visibleInventory.length ? <div className="inventory-list">{visibleInventory.map((item) => <InventoryCard key={item.id} item={item} onConsume={consumeItem} />)}</div> : <section className="empty-state"><span>🧊</span><h2>{filter === "urgent" ? "没有临期食材" : "冰箱还空着"}</h2><p>{filter === "urgent" ? "挺好，今天不用抢救剩菜。" : "扫一次冰箱，或者手动加一件。"}</p></section>}
        </TabsContent>

        <TabsContent value="shopping" className="tab-page manager-page">
          <section className="manager-heading"><div><span className="eyebrow"><ShoppingBasket size={14} /> 自动采购单</span><h1>只买缺的，<br /><b>不囤没用的。</b></h1></div><button className="round-button" onClick={() => void loadShopping()} aria-label="刷新采购单"><RefreshCw size={18} /></button></section>
          <section className="shopping-summary"><div><Sparkles size={18} /><span>根据库存和想做的菜自动更新</span></div><Button onClick={generateShopping}><WandSparkles size={16} /> 重新生成</Button></section>
          <div className="shopping-list">{shopping.map((item) => <label className={`shopping-row ${item.checked ? "checked" : ""}`} key={item.id}><Checkbox checked={Boolean(item.checked)} onCheckedChange={(value) => void toggleShopping(item.id, Boolean(value))} /><span className="shopping-emoji">{item.name.includes("蛋") ? "🥚" : item.name.includes("菜") ? "🥬" : "🛒"}</span><div><strong>{item.name}</strong><small>{item.amount} {item.unit} · {item.reason}</small></div>{item.autoGenerated ? <em>AI 加的</em> : <em className="manual">手动</em>}</label>)}</div>
          {!shopping.length && !loadingData && <section className="empty-state"><span>🧺</span><h2>采购单还是空的</h2><p>让 AI 根据库存补一张，或者手动记一件。</p><Button onClick={generateShopping}>自动生成一张</Button></section>}
          <div className="shopping-actions"><Dialog open={shoppingDialog} onOpenChange={setShoppingDialog}><DialogTrigger asChild><Button variant="secondary"><ListPlus size={17} /> 手动加一件</Button></DialogTrigger><DialogContent className="food-dialog"><DialogHeader><DialogTitle>加到采购单</DialogTitle></DialogHeader><div className="dialog-form"><label>要买什么<Input value={draftBuy.name} onChange={(e) => setDraftBuy({ ...draftBuy, name: e.target.value })} placeholder="比如：燕麦奶" /></label><div className="form-row"><label>数量<Input type="number" min="0.1" step="0.5" value={draftBuy.amount} onChange={(e) => setDraftBuy({ ...draftBuy, amount: e.target.value })} /></label><label>单位<Input value={draftBuy.unit} onChange={(e) => setDraftBuy({ ...draftBuy, unit: e.target.value })} /></label></div><Button onClick={addShopping}>记下来</Button></div></DialogContent></Dialog><Button disabled={!checkedShopping.length} onClick={finishShopping}><PackageCheck size={17} /> 买完入库 {checkedShopping.length ? `(${checkedShopping.length})` : ""}</Button></div>
        </TabsContent>

        <TabsList className="bottom-nav"><TabsTrigger value="cook"><Utensils size={19} /><span>今晚吃啥</span></TabsTrigger><TabsTrigger value="inventory" className="nav-with-badge"><Refrigerator size={19} /><span>我的库存</span>{urgentItems.length > 0 && <b>{urgentItems.length}</b>}</TabsTrigger><TabsTrigger value="shopping"><ShoppingBasket size={19} /><span>采购清单</span></TabsTrigger></TabsList>
      </Tabs>
      <footer className="product-footer"><span>照片默认不保存</span><a href="/privacy">隐私</a><a href="/terms">条款</a><a href="/account">同步账号</a></footer>
      <Toaster position="top-center" richColors />
    </main>
  );
}

function CookHome({ onDemo, onCamera, onGallery, inputRef, cameraRef, onFile, notice, stats, inventoryCount, modelStatus, mealGoal, onGoalChange }: { onDemo: () => void; onCamera: () => void; onGallery: () => void; inputRef: React.RefObject<HTMLInputElement | null>; cameraRef: React.RefObject<HTMLInputElement | null>; onFile: (file: File) => void; notice: string; stats: Stats; inventoryCount: number; modelStatus: ModelStatus; mealGoal: MealGoal; onGoalChange: (goal: MealGoal) => void }) {
  const goals: Array<{ id: MealGoal; emoji: string; name: string; note: string }> = [
    { id: "daily", emoji: "🍚", name: "日常", note: "均衡省事" },
    { id: "cut", emoji: "🥗", name: "减脂", note: "少油高蛋白" },
    { id: "gain", emoji: "💪", name: "增肌", note: "蛋白质优先" },
  ];
  return <div className="home-view"><section className="intro-copy"><div className="eyebrow"><Sparkles size={15} /> 今晚别点外卖</div><h1>冰箱里有啥，<br /><span>就吃啥。</span></h1><p>拍一下，AI 帮你认食材、看状态、排过期顺序，给出现在就能做的懒人菜。</p><div className="meal-goal-picker"><strong>今天怎么吃？</strong><div className="meal-goal-options" role="group" aria-label="选择饮食目标">{goals.map((goal) => <button key={goal.id} className={mealGoal === goal.id ? "active" : ""} aria-pressed={mealGoal === goal.id} onClick={() => onGoalChange(goal.id)}><b>{goal.emoji} {goal.name}</b><small>{goal.note}</small></button>)}</div></div></section><section className="scan-card"><img src="/fridge-night.png" alt="打开的日常冰箱，里面放着鸡蛋、蔬菜和剩饭" /><div className="scan-card-shade" /><div className={`live-chip ${modelStatus.configured ? "ready" : "offline"}`}><span /> {modelStatus.configured ? "DeepSeek 真实识别已启用" : "DeepSeek 识别待启用"}</div><div className="scan-frame" aria-hidden="true"><i /><i /><i /><i /></div><div className="scan-actions"><input ref={cameraRef} className="sr-only" type="file" accept="image/*" capture="environment" onChange={(e) => e.target.files?.[0] && onFile(e.target.files[0])} /><input ref={inputRef} className="sr-only" type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && onFile(e.target.files[0])} /><Button className="primary-action" size="lg" onClick={onCamera}><Camera size={20} /> 拍下我的冰箱</Button><Button className="gallery-action" variant="secondary" size="lg" onClick={onGallery} aria-label="从相册选择照片"><ImagePlus size={20} /></Button></div></section><button className="demo-link" onClick={onDemo}>没在冰箱旁？先看一次示例 <ChevronRight size={15} /></button>{notice && <p className="notice">{notice}</p>}<section className="challenge-card"><div className="challenge-icon"><Zap size={22} fill="currentColor" /></div><div><span>本周挑战</span><strong>让 AI 清空我的冰箱</strong></div><div className="challenge-score">{stats.itemsRescued || inventoryCount}<small> 样</small></div></section><section className="mini-proof"><div className="proof-avatars"><span>🍳</span><span>🥗</span><span>🍚</span></div><p><b>{stats.mealsCooked || 1} 顿</b> 没点外卖，都是冰箱救的</p><Leaf size={18} /></section></div>;
}

function Scanning({ preview, progress }: { preview: string | null; progress: number }) {
  return <section className="scanning-view" aria-live="polite"><div className="scanning-photo">{preview && <img src={preview} alt="正在识别的冰箱照片" />}<div className="scan-line" /><div className="scan-orbit"><WandSparkles size={28} /></div></div><div className="scan-copy"><span className="scanning-label"><LoaderCircle size={15} className="spin" /> AI 正在翻冰箱</span><h2>{progress < 45 ? "看看藏了什么…" : progress < 88 ? "正在看状态和搭配…" : "三道菜，马上好！"}</h2><Progress value={progress} className="scan-progress" /><p>{progress}% · 识别食材、观察状态、估计期限、计算省钱</p></div></section>;
}

function ResultView({ analysis, preview, notice, activeRecipe, setActiveRecipe, cooked, onCook, onReset, onSave, onShopping }: { analysis: Analysis; preview: string | null; notice: string; activeRecipe: number; setActiveRecipe: (n: number) => void; cooked: boolean; onCook: () => void; onReset: () => void; onSave: () => void; onShopping: () => void }) {
  const recipe = analysis.recipes[activeRecipe] ?? demoAnalysis.recipes[0];
  const [portionScale, setPortionScale] = useState(1);
  const [oilGrams, setOilGrams] = useState(recipe.oilGrams ?? 8);
  const goal = analysis.goal ?? "daily";
  const goalLabels: Record<MealGoal, string> = { daily: "日常模式", cut: "减脂模式", gain: "增肌模式" };
  const defaultGoalNotes: Record<MealGoal, string> = { daily: "主食、蔬菜和蛋白质尽量均衡。", cut: "少油、控制主食份量并优先蛋白质。", gain: "提高蛋白质和主食份量，方便训练后补充。" };
  const nutrition = useMemo(() => estimateRecipeNutrition({ ingredients: recipe.nutrition, baseCalories: recipe.calories, baseProtein: recipe.protein, baseOilGrams: recipe.oilGrams, portionScale, oilGrams }), [recipe, portionScale, oilGrams]);
  useEffect(() => { setPortionScale(1); setOilGrams(recipe.oilGrams ?? 8); }, [recipe.name, recipe.oilGrams]);
  return <div className="result-view">
    <div className="result-heading"><button className="back-button" onClick={onReset} aria-label="重新拍摄"><ArrowLeft size={20} /></button><div><span className="eyebrow"><Sparkles size={14} /> AI 看完了</span><h1>今晚能做 <b>{analysis.recipes.length} 道菜</b></h1></div><button className="round-button" onClick={onReset} aria-label="重新识别"><RotateCcw size={18} /></button></div>
    {analysis.mode === "live" && <div className="model-proof"><span /> DeepSeek 多模态真实识别</div>}
    {notice && <div className="mode-notice">{notice}</div>}
    <section className="fridge-summary">{preview ? <img src={preview} alt="本次识别的冰箱" /> : <div className="summary-placeholder">🥬</div>}<div><span>我的冰箱 · 刚刚</span><p>{analysis.summary}</p></div></section>
    <section className="ingredient-section"><div className="section-title"><h2>认出了 {analysis.items.length} 样</h2><span>状态为视觉估计</span></div><div className="ingredient-scroll">{analysis.items.map((item) => <article className="ingredient-card" key={item.name}><span className="food-emoji">{item.emoji}</span><strong>{item.name}</strong><small>{item.amount}</small><em className={freshnessClass[item.freshness]}>{item.freshness}</em>{item.condition && <p className="condition-note">{item.condition}</p>}</article>)}</div><div className="result-actions"><Button variant="secondary" onClick={onShopping}><ShoppingBasket size={16} /> 补齐采购单</Button><Button onClick={onSave}><Refrigerator size={16} /> 全部存入库存</Button></div></section>
    <section className="safety-card result-safety"><AlertTriangle size={17} /><p><b>别只信照片。</b>{analysis.safety_note || "异味、发黏、霉变或包装异常时不要食用。"}</p></section>
    <section className="recipe-section">
      <div className="section-title"><h2>选一道，展开菜谱</h2><span>点菜名切换完整步骤</span></div>
      <div className="recipe-switcher" aria-label="选择菜谱">{analysis.recipes.map((item, index) => { const estimate = estimateRecipeNutrition({ ingredients: item.nutrition, baseCalories: item.calories, baseProtein: item.protein, baseOilGrams: item.oilGrams, portionScale: 1, oilGrams: item.oilGrams ?? 8 }); return <button aria-pressed={activeRecipe === index} className={activeRecipe === index ? "active" : ""} key={item.name} onClick={() => setActiveRecipe(index)}><span>{item.emoji}</span><div><b>{item.name}</b><small>{item.time} 分钟 · {estimate.calorieLow}–{estimate.calorieHigh} 千卡</small></div><ChevronRight size={16} /></button>; })}</div>
      <div className={`recipe-hero recipe-expanded ${recipe.color}`} key={`${activeRecipe}-${recipe.name}`}>
        <div className="recipe-kicker"><span>{goalLabels[goal]}</span><b>{activeRecipe === 0 ? "最推荐" : "已选择"} · 能用掉 {recipe.uses.length} 样</b></div>
        <div className="recipe-main"><div><h3>{recipe.name}</h3><p>{recipe.subtitle}</p><div className="recipe-meta"><span><Clock3 size={15} /> {recipe.time} 分钟</span><span><Sparkles size={15} /> {recipe.difficulty}</span></div></div><span className="recipe-emoji">{recipe.emoji}</span></div>
        <div className="nutrition-strip"><span><b>{nutrition.calorieLow}–{nutrition.calorieHigh}</b><small>千卡 · 估算区间</small></span><span><b>{nutrition.proteinLow}–{nutrition.proteinHigh}g</b><small>蛋白质</small></span><p><strong>{goalLabels[goal]}</strong>{recipe.goalNote || defaultGoalNotes[goal]}</p></div>
        <div className="nutrition-editor">
          <div className="nutrition-editor-head"><div><strong>把热量算得更像你这顿</strong><small>{nutrition.source}</small></div><span>当前约 {nutrition.calories} 千卡</span></div>
          <div className="nutrition-control"><b>我的份量</b><div>{[{ value: .5, label: "半份" }, { value: 1, label: "1 份" }, { value: 1.5, label: "1.5 份" }, { value: 2, label: "2 份" }].map((option) => <button key={option.value} className={portionScale === option.value ? "active" : ""} onClick={() => setPortionScale(option.value)}>{option.label}</button>)}</div></div>
          <div className="nutrition-control"><b>这份用油</b><div>{[0, 5, 10, 15].map((grams) => <button key={grams} className={oilGrams === grams ? "active" : ""} onClick={() => setOilGrams(grams)}>{grams === 0 ? "不放油" : `${grams}g`}</button>)}</div></div>
          <div className="nutrition-assumptions"><strong>计算假设</strong><div>{nutrition.assumptions.length ? nutrition.assumptions.map((item) => <span key={item.name}>{item.name} {item.grams}g</span>) : recipe.uses.map((item) => <span key={item}>{item} · 份量为 AI 估计</span>)}<span>食用油 {oilGrams}g</span></div></div>
          <p className="nutrition-disclaimer">照片看不准隐藏的油、酱料和实际克数，所以给区间而不是假装精确；用于日常参考，不替代营养师或称重记录。</p>
        </div>
        <div className="use-row">{recipe.uses.map((item) => <span key={item}><Check size={13} /> {item}</span>)}</div>
        <ol className="steps">{recipe.steps.map((step, index) => <li key={step}><b>{index + 1}</b><span>{step}</span></li>)}</ol>
        <Button className={`cook-button ${cooked ? "done" : ""}`} onClick={onCook} disabled={cooked}>{cooked ? <><PartyPopper size={19} /> 已开饭，省下 ¥{recipe.saved}</> : <>就做这个 · 预计省 ¥{recipe.saved}<ChevronRight size={19} /></>}</Button>
      </div>
    </section>
    <div className="bottom-spacer" />
  </div>;
}

function InventoryCard({ item, onConsume }: { item: InventoryItem; onConsume: (id: string, action?: "consume" | "discard") => void }) {
  return <article className={`stock-card ${item.status}`}><div className="stock-emoji">{item.emoji}</div><div className="stock-main"><div className="stock-name"><h3>{item.name}</h3><span>{item.category}</span></div><p>{item.quantity} {item.unit} · {item.condition}</p><div className="stock-expiry"><span className="expiry-bar"><i style={{ width: item.daysLeft == null ? "35%" : `${Math.max(8, Math.min(100, (item.daysLeft / 7) * 100))}%` }} /></span><b>{item.label}</b></div><small>AI 状态把握 {Math.round(item.confidence * 100)}% · {item.source === "manual" ? "手动录入" : "来自识别"}</small></div><div className="stock-actions"><button onClick={() => onConsume(item.id)}><Check size={16} /> 吃掉了</button>{item.status === "expired" && <button className="discard" onClick={() => onConsume(item.id, "discard")} aria-label={`丢弃 ${item.name}`}><Trash2 size={15} /></button>}</div></article>;
}

function LoadingCards() { return <div className="inventory-list">{[1,2,3].map((n) => <div className="stock-card loading-card" key={n}><span /><div><i /><i /><i /></div></div>)}</div>; }
