import { NextResponse } from "next/server";
import { getD1 } from "@/db";
import { resolveOwner, withOwnerCookie } from "@/lib/owner";
import { eventStatement } from "@/lib/events";

function json(data: unknown, cookie: string | null, init?: ResponseInit) {
  return withOwnerCookie(NextResponse.json(data, init), cookie);
}

export async function GET(request: Request) {
  const { ownerId, cookie } = resolveOwner(request);
  const result = await getD1().prepare(`SELECT id, name, amount, unit, reason, checked,
    auto_generated AS autoGenerated, created_at AS createdAt
    FROM shopping_items WHERE owner_id = ? ORDER BY checked ASC, auto_generated DESC, created_at DESC`)
    .bind(ownerId).all();
  return json({ items: result.results }, cookie);
}

export async function POST(request: Request) {
  const { ownerId, cookie } = resolveOwner(request);
  const body = await request.json();
  const now = Date.now();

  if (body.action === "generate") {
    const inventory = await getD1().prepare(`SELECT name, category, quantity, min_quantity AS minQuantity,
      estimated_expires_at AS estimatedExpiresAt FROM inventory_items WHERE owner_id = ? AND status = 'active'`)
      .bind(ownerId).all();
    const active = (inventory.results as Array<Record<string, unknown>>).filter((item) => !item.estimatedExpiresAt || Number(item.estimatedExpiresAt) >= now);
    const names = new Set(active.map((item: Record<string, unknown>) => String(item.name)));
    const suggestions: Array<{ name: string; amount: number; unit: string; reason: string }> = [];

    for (const item of active) {
      if (Number(item.minQuantity) > 0 && Number(item.quantity) <= Number(item.minQuantity)) {
        suggestions.push({ name: String(item.name), amount: Math.max(1, Number(item.minQuantity) * 2 - Number(item.quantity)), unit: "份", reason: "库存快见底了" });
      }
    }
    const missing = Array.isArray(body.missing) ? body.missing.map(String).slice(0, 12) : [];
    for (const name of missing) if (!names.has(name)) suggestions.push({ name, amount: 1, unit: "份", reason: "想做的菜还缺它" });
    if (!active.some((item: Record<string, unknown>) => item.category === "蛋白质")) suggestions.push({ name: "鸡蛋", amount: 6, unit: "个", reason: "冰箱缺一份万能蛋白质" });
    if (!active.some((item: Record<string, unknown>) => item.category === "蔬菜")) suggestions.push({ name: "时令蔬菜", amount: 1, unit: "把", reason: "库存里没有新鲜蔬菜" });
    if (!active.some((item: Record<string, unknown>) => item.category === "主食")) suggestions.push({ name: "挂面", amount: 1, unit: "袋", reason: "补一个耐放的应急主食" });

    const unique = [...new Map(suggestions.map((item) => [item.name, item])).values()].slice(0, 10);
    if (unique.length) {
      await getD1().batch([...unique.map((item) => getD1().prepare(`INSERT INTO shopping_items
        (id, owner_id, name, amount, unit, reason, checked, auto_generated, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, 0, 1, ?, ?)
        ON CONFLICT(owner_id, name) DO UPDATE SET amount = excluded.amount, unit = excluded.unit,
          reason = excluded.reason, checked = 0, auto_generated = 1, updated_at = excluded.updated_at`)
        .bind(crypto.randomUUID(), ownerId, item.name, item.amount, item.unit, item.reason, now, now)), eventStatement(ownerId, "shopping_generated", { count: unique.length })]);
    }
    return json({ ok: true, generated: unique.length }, cookie);
  }

  const name = String(body.name || "").trim().slice(0, 40);
  if (!name) return json({ error: "要买什么？" }, cookie, { status: 400 });
  await getD1().prepare(`INSERT INTO shopping_items
    (id, owner_id, name, amount, unit, reason, checked, auto_generated, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, '手动添加', 0, 0, ?, ?)
    ON CONFLICT(owner_id, name) DO UPDATE SET checked = 0, amount = excluded.amount, unit = excluded.unit, updated_at = excluded.updated_at`)
    .bind(crypto.randomUUID(), ownerId, name, Number(body.amount || 1), String(body.unit || "份"), now, now).run();
  return json({ ok: true }, cookie);
}

export async function PATCH(request: Request) {
  const { ownerId, cookie } = resolveOwner(request);
  const body = await request.json();
  const id = String(body.id || "");
  if (body.action === "clear_checked") {
    await getD1().prepare(`DELETE FROM shopping_items WHERE owner_id = ? AND checked = 1`).bind(ownerId).run();
  } else {
    await getD1().prepare(`UPDATE shopping_items SET checked = ?, updated_at = ? WHERE id = ? AND owner_id = ?`)
      .bind(body.checked ? 1 : 0, Date.now(), id, ownerId).run();
  }
  return json({ ok: true }, cookie);
}
