import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const inventoryItems = sqliteTable("inventory_items", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("🥬"),
  category: text("category").notNull().default("其他"),
  quantity: real("quantity").notNull().default(1),
  unit: text("unit").notNull().default("份"),
  minQuantity: real("min_quantity").notNull().default(0),
  estimatedExpiresAt: integer("estimated_expires_at", { mode: "timestamp_ms" }),
  condition: text("condition").notNull().default("看起来正常"),
  confidence: real("confidence").notNull().default(0.6),
  source: text("source").notNull().default("manual"),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("inventory_owner_status_idx").on(table.ownerId, table.status),
  uniqueIndex("inventory_owner_name_active_idx").on(table.ownerId, table.name, table.status),
]);

export const shoppingItems = sqliteTable("shopping_items", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  name: text("name").notNull(),
  amount: real("amount").notNull().default(1),
  unit: text("unit").notNull().default("份"),
  reason: text("reason").notNull().default("手动添加"),
  checked: integer("checked", { mode: "boolean" }).notNull().default(false),
  autoGenerated: integer("auto_generated", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("shopping_owner_checked_idx").on(table.ownerId, table.checked),
  uniqueIndex("shopping_owner_name_idx").on(table.ownerId, table.name),
]);

export const userStats = sqliteTable("user_stats", {
  ownerId: text("owner_id").primaryKey(),
  totalSaved: integer("total_saved").notNull().default(0),
  itemsRescued: integer("items_rescued").notNull().default(0),
  mealsCooked: integer("meals_cooked").notNull().default(0),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const userProfiles = sqliteTable("user_profiles", {
  ownerId: text("owner_id").primaryKey(),
  email: text("email").notNull().unique(),
  displayName: text("display_name"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull(),
});

export const scanEvents = sqliteTable("scan_events", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  clientHash: text("client_hash").notNull(),
  status: text("status").notNull().default("started"),
  model: text("model").notNull(),
  itemCount: integer("item_count").notNull().default(0),
  latencyMs: integer("latency_ms").notNull().default(0),
  errorCode: text("error_code"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("scan_owner_created_idx").on(table.ownerId, table.createdAt),
  index("scan_client_created_idx").on(table.clientHash, table.createdAt),
  index("scan_status_created_idx").on(table.status, table.createdAt),
]);

export const productEvents = sqliteTable("product_events", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  eventName: text("event_name").notNull(),
  metadata: text("metadata"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("product_event_owner_created_idx").on(table.ownerId, table.createdAt),
  index("product_event_name_created_idx").on(table.eventName, table.createdAt),
]);

export const feedback = sqliteTable("feedback", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  kind: text("kind").notNull().default("idea"),
  content: text("content").notNull(),
  contact: text("contact"),
  status: text("status").notNull().default("new"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("feedback_status_created_idx").on(table.status, table.createdAt),
  index("feedback_owner_created_idx").on(table.ownerId, table.createdAt),
]);
